#!/bin/bash

export TERMINAL="kitty"

feh --bg-fill ~/Sync/custom/leaves.jpeg

# Easily find hotkey scripts
set PATH="$XDG_CONFIG_HOME/.berry:$PATH"

# Set decoration geometry
berry b_width 0
berry i_width 0
berry t_height 18
berry bottom_height 8

# Set decoration colors
berry bf_color b6b80b
berry bu_color 604040
berry if_color b6b80b
berry iu_color 604040

fcitx5 -d
volctl &
picom &
tint2 &
dunst &
discord &
steam & # seems to crash tint2 :(
