#!/bin/bash

export TERMINAL="kitty"

feh --bg-fill ~/Sync/custom/moss.jpeg

# Set decoration geometry
berryc border_width     0
berryc title_height     32
berryc draw_text        0
berryc top_gap          32
berryc inner_border_width  0

# Set decoration colors
berryc focus_color         b3be5a
berryc unfocus_color       604040
berryc inner_focus_color   b3be5a
berryc inner_unfocus_color 604040
berryc text_focus_color    000000
berryc text_unfocus_color  000000

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "false"
berryc set_font    "Dina-12"

sxhkd -c ~/.config/berry/sxhkdrc &
fcitx5 -d
picom &
#polybar -r &
tint2 &
dunst &
volctl &
