#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config focused_border_color "#b3be5a"

bspc config border_width         3
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config kill_orphaned_on_exit true

bspc monitor -d 1 2 3 4

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill ~/Sync/custom/leaves.jpeg
fcitx5 -d
picom &
polybar -r &
dunst &
volctl &
xsetroot -cursor_name left_ptr
