#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d dev web comm steam
bspc config focused_border_color "#ac4142"

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config kill_orphaned_on_exit true

bspc monitor -d 1 2 3 4

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill ~/Sync/custom/leaves.jpeg
#feh --bg-scale ~/Sync/custom/leaves.jpeg #this works but can distort sthe image
fcitx5 -d
picom &
polybar -r &
dunst &
xsetroot -cursor_name left_ptr
